// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BpAddComp: typeof import('./src/components/BpForm/BpAddComp.vue')['default']
    BpAddSubComp: typeof import('./src/components/BpForm/BpAddSubComp.vue')['default']
    BpButtonComp: typeof import('./src/components/BpButton/BpButtonComp.vue')['default']
    BpForm: typeof import('./src/components/BpForm/index.vue')['default']
    BpInputComp: typeof import('./src/components/BpForm/BpInputComp.vue')['default']
    BpSub: typeof import('./src/components/BpForm/BpSub.vue')['default']
    BpSubComp: typeof import('./src/components/BpForm/BpSubComp.vue')['default']
    BpSwiperComp: typeof import('./src/components/BpSwiper/BpSwiperComp.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    GlobalLoading: typeof import('./src/components/GlobalLoading/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Menu: typeof import('./src/components/TopBar/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/TopBar/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
